spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsletter
    username: docker
    password: docker
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: true
    location: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000